### ISSUE TITLE
Не совпадает хэш

### ISSUE THREAD

**Issue by juralis** [andviro/go-cryptoapi#1]
Доброго дня и прошу прощения, что беспокою!

Строго говоря, я не вполне на счёт этой библиотеки, но на счёт её [родственника](https://bitbucket.org/andviro/cpro-py) на python. Просто не смог найти, куда ещё вам можно написать.

Дело вот в чём. На [тестовой странице](https://www.cryptopro.ru/sites/default/files/products/cades/demopage/cades_xmldsig_sample.html) браузерного плагина от КриптоПро имеется возможность сформировать подписанный xml. В нём содержится хэш и подпись первоначальных данных. В вашей библиотеке есть возможность их сформировать. Но по какой-то причине, хэш на странице с примером и производимый вашей библиотекой - отличаются. Подпись сформированная на странице плагина тоже не проверяется в вашей библиотеке. В принципе, оно и понятно - на сколько я понимаю, подписывается ведь сам хэш, а не данные. таким образом, при различии хэшей подпись тоже не пройдёт проверку.

Скажем, для строки:
```
<?xml version="1.0" encoding="UTF-8"?><Envelope>text</Envelope>
```
Плагин подсчитает такой хэш:
nn/sSaGHg+OeIqw5EJ4qtsi2xJJDLcDU84FgKCoFBKM=

Если посчитать хэш той же строки в вашей библиотеке, то получится так:

```
data = b'<?xml version="1.0" encoding="UTF-8"?><Envelope>text</Envelope>'
hash = cryptoapi.Hash(data)
dig = hash.digest()
print(dig.encode('base64'))
```
 MxkoN5EoqG41Jhwa9evAj0HVVEqOVGnF9MKAW+Vsd4Y=

Что не вполне одно и тоже. и я никак не могу понять в чём тут может быть причина?

**Comment by andviro** [comment]
Добрый день! Хэш-функции проверялись для тестовых строк, приведенных в Википедии для  [ГОСТ Р 34.11-94](https://ru.wikipedia.org/wiki/%D0%93%D0%9E%D0%A1%D0%A2_%D0%A0_34.11-94#.D0.9D.D0.B0.D0.B1.D0.BE.D1.80_.D0.BF.D0.B0.D1.80.D0.B0.D0.BC.D0.B5.D1.82.D1.80.D0.BE.D0.B2_CryptoPro), это можно подсмотреть в юнит-тестах, файл tests/test_csp.py. Попробуйте, кстати, ввести плагину в качестве тестовой строки "The quick brown fox jumps over the lazy dog". Должно получиться 9004294A361A508C586FE53D1F1B02746765E71B765472786E4770D565830A76

А Вам точно нужен именно хэш? Обычно из плагина получают отсоединенную подпись в PKCS7. Ее можно проверить, например, функцией cryptoapi.check_signature() или низкоуровневыми функциями из модуля csp.

**Comment by juralis** [comment]
Прошу прощения - это я не разобрался что к чему. Оказалось, что хэш берётся не от всей строки, а только от '\<Envelope>text\</Envelope>', а '\<?xml version="1.0" encoding="UTF-8"?>' - отбрасывается. 

Да, про отсоединяемую подпись - это понятно. Просто тут используется xmldsig, а там берётся хэш, подписывается и всё это пакуется в этот же xml. Я почему-то думал, что подписывается первоначальный вариант xml, а там есть ещё некоторые преобразования перед вычислением хэша.
