### ISSUE TITLE
Электронная подпись

### ISSUE THREAD

**Issue by RadnaevMB** [andviro/go-cryptoapi#10]
Здравствуйте возможно ли получить помощь?

**Comment by andviro** [comment]
А можно поконкретнее?

**Comment by RadnaevMB** [comment]
Здравствуйте, у нас своя медицинская информационная система, сейчас стоит задача подписывание документов 
электронными подписями. У нас возникли проблемы, на серверной части используем go на клиенте vuejs. Например  https://cabinets.fss.ru/eln.html  интересует вкладка «Сервисы для мед. организации». 
>Вторник, 21 января 2020, 16:13 +03:00 от Andrew Rodionoff <notifications@github.com>:
> 
>А можно поконкретнее?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Munko Radnaev

**Comment by andviro** [comment]
Если подписывает клиент из веб-приложения, то надо смотреть в сторону плагинов к браузеру, т.к. ключ будет на стороне клиента. Можно на сайте того же КриптоПро поискать.
 
Если подписывает своим ключом сервер, то посмотрите примеры из юнит-тестов, там есть формирование подписи. msg_test.go, функция TestMsgEncode показывает, как подписывать с записью в io.Writer на примере bytes.Buffer. Ну и там же проверка подписи с извлечением содержимого контейнера.
