### ISSUE TITLE
Серверный сертификат

### ISSUE THREAD

**Issue by RadnaevMB** [andviro/go-cryptoapi#11]
Здравствуйте поставили задачу подписывать xml документы серверным сертификатом. Изучаю Ваш код пока мало что понятно). Есть ли у Вас пример какой нибудь? Или Вы берете платно задачи?

**Comment by andviro** [comment]
Здравствуйте. Пока нет свободного времени ни на платные ни на какие-то иные задачи. Как пример использования можно взять юнит-тесты, там основной функционал покрыт, msg_test.go например. Что касается XML, то если стоит задача выработать XML-DSIG, то в библиотечке пока не хватает функций и объектов для подписанных хешей, которые там используются. Тоже руки не доходят, к сожалению.
