### ISSUE TITLE
При сборке выдает сообщение несовместимости типов 

### ISSUE THREAD

**Issue by jelaev** [andviro/go-cryptoapi#4]
go get github.com/andviro/go-cryptoapi/csp
andviro\go-cryptoapi\csp\msg.go:197: cannot use &hCryptProv (type *C.HCRYPTPROV) as type *C.HCRYPTPROV_OR_NCRYPT_KEY_HANDLE in argument to func literal

**Comment by andviro** [comment]
Go 1.9? Еще не проверял с ним, посмотрим.

**Comment by jelaev** [comment]
go version go1.8.3 windows/amd64

**Comment by andviro** [comment]
попробуйте в новой версии, вроде билдится

**Comment by jelaev** [comment]
go version go1.9 windows/amd64
Да, собралось. Пример запустился. Спасибо.

**Comment by andviro** [comment]
отлично, закрываем
