### ISSUE TITLE
Как забилдить на macOS?

### ISSUE THREAD

**Issue by importnil** [andviro/go-cryptoapi#5]
Привет! Реально ли забилдить творение на macOS? Добрался до такой ошибки при компиляции:

```
# github.com/andviro/go-cryptoapi/csp
cgo-gcc-prolog:56:3: error: unknown type name 'BOOL'
cgo-gcc-prolog:78:3: error: unknown type name 'BOOL'
```

Спасибо.

**Comment by andviro** [comment]
Привет. Скорее всего не получится прямо в макоси, для *nix предполагается установленный CryptoPro Linux SDK. Можно в образе Docker попробовать сделать, предварительно туда установив.
