### ISSUE TITLE
WinCryptEx.h

### ISSUE THREAD

**Issue by v0ld-dev** [andviro/go-cryptoapi#8]
Добрый день
Пытаюсь получить C.CALG_G28147 но безуспешно тк не ипортирована WinCryptEx.h
При попытке импортировать WinCryptEx.h (работаю в linux) вылетает ошибка /opt/cprocsp/include/cpcsp/WinCryptEx.h:36:10: fatal error: wincrypt.h: No such file or directory
Ниже кусок кода в месте где спотыкаемся:
33 #if defined UNIX || defined CSP_LITE
34 #include "CSP_WinCrypt.h"
35 #else // UNIX
36 #include <wincrypt.h>
37 #endif // UNIX

Почему он уходит в else ?

**Comment by andviro** [comment]
Привет. Что-то с установкой dev-пакета КриптоПро. Версия какая?

**Comment by andviro** [comment]
хотя переменные gcc/cgo выставлять должен
Версия go тоже интересно.

**Comment by v0ld-dev** [comment]
Вот все что я поставил отноcительно dpkg -l | grep csp:

ii  cprocsp-cpopenssl-64                            4.0.0-4                                      amd64        OpenSSL. Build 9842.
ii  cprocsp-cpopenssl-base                          4.0.0-4                                      all          Openssl common Build 9842.
ii  cprocsp-cpopenssl-gost-64                       4.0.0-4                                      amd64        OpenSSL capi_gost engine. Build 9842.
ii  cprocsp-curl-64                                 4.0.0-4                                      amd64        CryptoPro Curl shared library and binaris. Build 9842.
ii  cprocsp-rdr-gui-gtk-64                          4.0.0-4                                      amd64        GUI components for CryptoPro CSP readers. Build 9842.
ii  cprocsp-rdr-pcsc-64                             4.0.0-4                                      amd64        PC/SC components for CryptoPro CSP readers. Build 9842.
ii  cprocsp-rsa-64                                  4.0.0-4                                      amd64        CryptoPro RSA CSP. Build 9842.
ii  cprocsp-stunnel-64                              4.0.0-4                                      amd64        Universal SSL/TLS tunnel.
ii  lsb-cprocsp-base                                4.0.0-4                                      all          CryptoPro CSP library. Build 9842.
ii  lsb-cprocsp-capilite-64                         4.0.0-4                                      amd64        CryptoAPI lite. Build 9842.
ii  lsb-cprocsp-devel                               4.0.0-5                                      all          CryptoPro CSP static libraries and headers. Build 9842.
ii  lsb-cprocsp-kc1-64                              4.0.0-4                                      amd64        CryptoPro CSP library. Build 9842.
ii  lsb-cprocsp-rdr-64                              4.0.0-4                                      amd64        CryptoPro CSP readers. Build 9842.

**Comment by v0ld-dev** [comment]
Версия: 
go version go1.11.1 linux/amd64

**Comment by andviro** [comment]
Что-то с gcc, получается. А из devel-пакета собираются примеры?

**Comment by v0ld-dev** [comment]
Да. Через eval `/opt/cprocsp/src/doxygen/setenv.sh --64`; make -f Makefile.unix
Все собирается и работает.
Есть идеи ) ?

**Comment by andviro** [comment]
чудно. Как-то оно предполагалось, что из коробки собирается. А если этот setenv.sh вызвать перед go build?

**Comment by sitenative** [comment]
Добрый день!
Как правильно импортировать WinCryptEx.h?
При попытке установки пакета получаю:

```
GOROOT=C:\Users\User\go\go1.15 #gosetup
GOPATH=C:\Users\User\go #gosetup
C:\Users\User\go\go1.15\bin\go.exe get -t -v github.com/andviro/go-cryptoapi/csp/... #gosetup
github.com/andviro/go-cryptoapi/csp
# github.com/andviro/go-cryptoapi/csp
In file included from C:\Users\User\go\src\github.com\andviro\go-cryptoapi\csp\cert.go:3:
./common.h:24:10: fatal error: WinCryptEx.h: No such file or directory
   24 | #include <WinCryptEx.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

**Comment by andviro** [comment]
Добрый день. Этот файл содержится в поставке cryptopro для linux, в dev-пакете. В репозиторий включить его не могу, по понятным причинам.

**Comment by TimurAs** [comment]
У меня такая же проблема на CSP 5.0 в сборке под Linux (Ubuntu 20.04)

33 #if defined UNIX || defined CSP_LITE
34 #include "CSP_WinCrypt.h"
35 #else // UNIX
36 #include <wincrypt.h>
37 #endif // UNIX

Уходит в  #include <wincrypt.h>, и ругается, что не моГёт найти.
Что делать то, товарищи?
Поставить CSP 3.6 ?

**Comment by andviro** [comment]
Все работает с 5.0. Правда, у меня убунта. За rpm-based не могу сказать с уверенностью. В докере билдится, кстати сказать, без проблем.

**Comment by VeronicaSharien** [comment]
Добрый день!
Такая же проблема, в версии 5.0. Приложение собираю через Qt Creator на Windows, но работает оно на устройстве с Sailfish OS.
Как поправить?

> error: wincrypt.h: No such file or directory #include <wincrypt.h>

WinCryptEx.h

`#if defined UNIX || defined CSP_LITE`
`#include "CSP_WinCrypt.h"`
`#else // UNIX`
`#include <wincrypt.h>`
`#endif // UNIX`

**Comment by andviro** [comment]
wincrypt.h, если не ошибаюсь, идет со стандартным CryptoAPI 2.0 под виндой. Не могу сказать за Qt Creator, наверное там надо копать что-то доуставить. Не пользуюсь компиляторами под Windows, не могу сказать точно.
